include: package:flutter_lints/flutter.yaml

analyzer:
  plugins:
    - custom_lint

  exclude:
  #   - test/.test_coverage.dart
  #   - lib/generated_plugin_registrant.dart
  #   - lib/l10n/**
    - lib/**/*.g.dart
  #   - lib/**/*.freezed.dart
  #   - test/**/*.g.dart

