name: flutter_map_simtaru
description: A new Flutter project.

publish_to: "none"
version: 1.0.4+4

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_map: ^5.0.0
  latlong2: ^0.9.0
  flutter_map_line_editor: ^5.0.0
  flutter_map_dragmarker: ^5.0.0
  go_router: ^10.1.2
  flutter_svg: ^2.0.7
  carousel_slider: ^4.2.1
  fl_chart: ^0.63.0
  hooks_riverpod: ^2.4.0
  flutter_hooks: ^0.20.1
  equatable: ^2.0.5
  tuple: ^2.0.2
  flutter_cache_manager: any
  fixnum: ^1.0.0
  protobuf: ^2.1.0
  persistent_bottom_nav_bar: ^5.0.2
  introduction_screen: ^3.1.11
  dots_indicator: ^2.1.2
  badges: ^3.1.2
  riverpod_annotation:
  shared_preferences:
  freezed_annotation:
  json_annotation:
  cupertino_icons: ^1.0.2
  dio: ^5.3.2
  another_flushbar: ^1.12.30
  shimmer: ^3.0.0
  intl: ^0.18.1
  file_picker: ^5.5.0
  open_file: ^3.3.2
  # flutter_file_downloader: ^1.1.4
  flutter_downloader: ^1.11.4
  # flutter_file_downloader: ^1.2.0-dev.1
  permission_handler: ^11.0.1
  loader_overlay: ^2.3.2
  device_info_plus: ^9.1.0
  quickalert: ^1.0.2
  flutter_expandable_fab: ^2.0.0
  flutter_map_geojson: 1.0.3
  webview_flutter: ^4.4.1
  url_launcher: ^6.2.1
  connectivity_plus: ^5.0.1
  path_provider: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  custom_lint: ^0.4.0
  build_runner: ^2.4.6
  go_router_builder: ^2.3.1
  freezed:
  json_serializable:
  riverpod_generator:
  flutter_native_splash:
  flutter_launcher_icons: ^0.13.1
  rename: ^3.0.1


flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/svg/
    - assets/svg/pengajuan_status/
    - assets/images/
    - assets/json/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Thin.ttf
          weight: 100
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600

# flutter_native_splash-development.yaml
flutter_native_splash:
  color: "#ffffff"
  image: assets/images/splash_screen.png
  branding: assets/images/splash_screen.png
  color_dark: "#121212"
  image_dark: assets/images/splash_screen.png
  branding_dark: assets/images/splash_screen.png

  android_12:
    image: assets/images/splash_screen.png
    icon_background_color: "#ffffff"
    image_dark: assets/images/splash_screen.png
    icon_background_color_dark: "#121212"

  web: false

flutter_launcher_icons:
  android: true
  image_path: "assets/images/launcher.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
