name: flutter_map_simtaru
description: A new Flutter project.

publish_to: "none" 
version: 1.0.0+1

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_map: ^4.0.0
  latlong2: ^0.8.0
  flutter_map_line_editor: ^5.0.0
  go_router: ^10.1.2
  flutter_svg: ^2.0.7
  carousel_slider: ^4.2.1
  fl_chart: ^0.63.0
  hooks_riverpod: ^2.4.0
  flutter_hooks: ^0.20.1
  equatable: ^2.0.5
  tuple: ^2.0.2
  flutter_cache_manager: any
  fixnum: ^1.0.0
  protobuf: ^2.1.0
  persistent_bottom_nav_bar: ^5.0.2
  introduction_screen: ^3.1.11
  dots_indicator: ^2.1.2
  badges: ^3.1.2
  riverpod_annotation:
  shared_preferences:
  freezed_annotation:
  json_annotation:
  cupertino_icons: ^1.0.2
  flutter_native_splash:
  dio: ^5.3.2
  another_flushbar: ^1.12.30

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  custom_lint: ^0.4.0
  build_runner: ^2.4.6
  go_router_builder: ^2.3.1
  freezed:
  json_serializable:
  riverpod_generator:

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/svg/
    - assets/images/
    - assets/json/
  
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Thin.ttf
          weight: 100
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/splash_screen.png
  android: true
  ios: true
  android_12:
    image: assets/images/splash_screen.png
    foreground_color: "#ffffff"
