// ignore_for_file: non_constant_identifier_names

import 'package:freezed_annotation/freezed_annotation.dart';

part 'pengajuan.freezed.dart';
part 'pengajuan.g.dart';

@freezed
class Pengajuan with _$Pengajuan {
  const factory Pengajuan({
    required int id,
    @Default(-1) int? user_id,
    @Default(-1) int? status_id,
    @Default('') String? alasan_ditolak,
    @Default('') String? revisi_berkas,
    @Default('') String? nama_lengkap,
    @Default('') String? alamat,
    @Default('') String? tempat_tanggal_lahir,
    @Default('') String? pekerjaan,
    @Default('') String? no_identitas,
    @Default('') String? no_hp,
    @Default('') String? bertindak_atas_nama,
    @Default('') String? penggunaan_tanah_saat_dimohon,
    @Default('') String? luas_tanah_seluruhnya,
    @Default('') String? luas_tanah_yang_dimohon,
    @Default('') String? bukti_penguasaan_tanah,
    @Default('') String? letak_tanah,
    @Default('') String? rencana_penggunaan_tanah,
    @Default('') String? batas_sebelah_utara,
    @Default('') String? batas_sebelah_timur,
    @Default('') String? batas_sebelah_selatan,
    @Default('') String? batas_sebelah_barat,
    @Default('') String? titik_koordinat,
    @Default('') String? desa,
    @Default('') String? kecamatan,
    @Default('') String? topografi_tanah,
    @Default('') String? kesuburan_tanah,
    @Default('') String? sarana_irigasi_atau_sumurbor,
    @Default('') String? jarak_bangunan_dengan_sungai,
    @Default('') String? jarak_bangunan_dengan_jalan,
    @Default('') String? status_kepemilikan,
    @Default('') String? luas_tanah_yang_disetujui,
    @Default('') String? kesesuaian_rencana,
    @Default('') String? hubungan_pemohon_dengan_tanah,
    @Default('') String? kesesuaian_dengan_keadaan_fisik_tanah,
    @Default('') String? tanah_yang_dimohon_fisiknya,
    @Default('') String? jarak_dari_pemukiman_terdekat,
    @Default('') String? pertimbangan,
    @Default('') String? tanggal_peninjauan_lokasi,
    @Default('') String? tanggal_turun_nota_dinas,
    @Default('') String? tanggal_turun_surat_rekomendasi,
    @Default('') String? no_ba,
    @Default('') String? no_nota_dinas,
    @Default('') String? no_surat_rekomendasi,
    @Default('') String? fotocopy_ktp,
    @Default('') String? fotocopy_sertifikat,
    @Default('') String? fotocopy_sppt_pbb,
    @Default('') String? fotocopy_npwp,
    @Default('') String? surat_persetujuan_tetangga,
    @Default('') String? gambar_rencana_pembangunan,
    @Default('') String? fotocopy_akte_pendirian_perusahaan,
    @Default('') String? set_lokasi_bangunan,
    @Default('') String? surat_pernyataan_force_majeur,
    @Default('') String? proposal,
    @Default('') String? foto_dokumentasi,
    @Default('') String? surat_pernyataan,
    @Default('') String? surat_permohonan_skpr,
    @Default('') String? surat_permohonan_tkprd,
    @Default('') String? berita_acara,
    @Default('') String? file_dokumentasi,
    @Default('') String? nota_dinas,
    @Default('') String? surat_hasil_rekomendasi,
    @Default('') String? scan_surat_hasil_rekomendasi,
    @Default('') String? titik_polygon,
    @Default(-1) int? jenis_tanah_id,
    @Default('') String? luas_bangunan,
    @Default('') String? tinggi_bangunan,
    @Default('') String? rencana_jalan,
    required DateTime created_at,
    required DateTime updated_at,
  }) = _Pengajuan;

  factory Pengajuan.fromJson(Map<String, dynamic> json) =>
      _$PengajuanFromJson(json);
}
